# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.7'
  pod 'Toast', '~> 4.0.0'
  pod 'SDWebImage', '~> 4.0'

  # Pods for GitTest

  target 'GitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitTestUITests' do
    # Pods for testing
  end

end
